### ISSUE TITLE
Schedule summer meeting

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/modeling-heterogeneity#8]
@embeukes @meghop @morganbale what would be a good time for you all to meet over the summer, if you're interested in working on it over the summer?

**Comment by embeukes** [comment]
@marcdotson @meghop @morganbale I'm free anytime this week after 2:30. After that I'll be traveling.

**Comment by marcdotson** [comment]
We should have data this week, then modeling can begin in earnest. If you're interested in working on the project, just let me know. :)
